export{default as Error404} from './404/404'
export{default as Details} from './Details/Details'
export{default as Explore} from './Explore/Explore'
export{default as Home} from './Home/Home'
export{default as SearchResult} from './SearchResult/SearchResult'