export{default as PageNotFound} from './404/PageNotFound'
export{default as Details} from './Details/Details'
export{default as Explore} from './Explore/Explore'
export{default as Home} from './Home/Home'
export{default as SearchResult} from './SearchResult/SearchResult'